# Generated by Django 4.2.4 on 2023-09-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="default_image.jpg", upload_to="product_images/"
            ),
        ),
    ]
